Description: "Simple Detector resource containing inline Rule, EventType, Variable, EntityType and Label resource definitions"
Parameters:
  S3Path:
    Default: "s3://fraud-sample-data/input/"
    Description: "path to folder containing data in S3 for glue crawler"
    Type: "String"
Resources:
  FraudDetector:
    Type: AWS::FraudDetector::Detector
    Properties:
      DetectorId: "fraud_detector_demo"
      Description: "A detector defined and created in a CloudFormation stack"
      DetectorVersionStatus: ACTIVE
      Rules:
        - RuleId: "investigate"
          Description: "investigate outcome if model score above 890"
          DetectorId: "fraud_detector_demo"
          Expression: "$amt > 900"
          Language: "DETECTORPL"
          Outcomes:
            - Name: "high_risk"
              Inline: true
        - RuleId: "review"
          Description: "reviews transactions between model score 700 and 900"
          DetectorId: "fraud_detector_demo"
          Expression: "$amt < 900 and $amt > 700"
          Language: "DETECTORPL"
          Outcomes:
            - Name: "medium_risk"
              Inline: true
        - RuleId: "approve"
          Description: "automatically approve transaction below model score 700"
          DetectorId: "fraud_detector_demo"
          Expression: "$amt < 700"
          Language: "DETECTORPL"
          Outcomes:
            - Name: "low_risk"
              Inline: true
      EventType:
        Inline: "true"
        Name: "credit_card_transaction"
        EventVariables:
          - Name: "trans_num"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "ORDER_ID"
            Inline: 'true'
          - Name: "job"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "CATEGORICAL"
            Inline: 'true'
          - Name: "city_pop"
            DataSource: 'EVENT'
            DataType: 'FLOAT'
            DefaultValue: '0.0'
            VariableType: "NUMERIC"
            Inline: 'true'
          - Name: "amt"
            DataSource: 'EVENT'
            DataType: 'FLOAT'
            DefaultValue: '0.0'
            VariableType: "PRICE"
            Inline: 'true'
          - Name: "street"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "BILLING_ADDRESS_L1"
            Inline: 'true'
          - Name: "cc_num"
            DataSource: 'EVENT'
            DataType: 'FLOAT'
            DefaultValue: '0.0'
            VariableType: "NUMERIC"
            Inline: 'true'
          - Name: "gender"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "CATEGORICAL"
            Inline: 'true'
          - Name: "merchant"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "CATEGORICAL"
            Inline: 'true'
          - Name: "last"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "BILLING_NAME"
            Inline: 'true'
          - Name: "first"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "BILLING_NAME"
            Inline: 'true'
          - Name: "state"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "BILLING_STATE"
            Inline: 'true'
          - Name: "city"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "BILLING_CITY"
            Inline: 'true'
          - Name: "zip"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "BILLING_ZIP"
            Inline: 'true'
          - Name: "category"
            DataSource: 'EVENT'
            DataType: 'STRING'
            DefaultValue: 'null'
            VariableType: "PRODUCT_CATEGORY"
            Inline: 'true'
        EntityTypes:
          - Name: "customer"
            Inline: 'true'
        Labels:
          - Name: "legit"
            Inline: 'true'
          - Name: "fraud"
            Inline: 'true'
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/scripts/fraud-etl-glue.py"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        "--fraud_samples": 12
        "--legit_samples": 130
        "--bucket": "fraud-sample-data"
        "--train-source-key": "s3://fraud-sample-data/input/fraudTrain.csv"
        "--test-source-key": "s3://fraud-sample-data/input/fraudTest.csv'"
        "--train-dest-key": "s3://fraud-sample-data/input/fraudTrain_glue_transformed.csv"
        "--test-dest-key": "s3://fraud-sample-data/input/fraudTest_glue_transformed.csv"
        "--train_max_cut_off": "2020-04-30 00:00:00"
        "--test_min_cut_off": "2020-08-30 00:00:00"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      GlueVersion: 3.0
      WorkerType: Standard
      NumberOfWorkers: 2
      Timeout: 15
      Name: glue-etl-fraud
      Role: !ImportValue RoleGlue-Arn
  GlueClassifier:
    Type: AWS::Glue::Classifier
    Properties:
      CsvClassifier:
        ContainsHeader: PRESENT
        Delimiter: ','
        Header:
          - index
          - trans_date_trans_time
          - cc_num
          - merchant
          - category
          - amt
          - first
          - last
          - gender
          - street
          - city
          - state
          - zip
          - lat
          - long
          - city_pop
          - job
          - dob
          - trans_num
          - unix_time
          - merch_lat
          - merch_long
          - is_fraud
        Name: "FraudClassifier"
  TrainDataCrawler:
      Type: AWS::Glue::Crawler
      Properties:
        Name: "train-crawler-fraud"
        DatabaseName: "default"
        Classifiers:
          - !Ref GlueClassifier
        Targets:
          S3Targets:
            - Path: !Ref S3Path
            - Exclusions: ["fraudTest.csv"]
        SchemaChangePolicy:
          UpdateBehavior: "UPDATE_IN_DATABASE"
          DeleteBehavior: "DELETE_FROM_DATABASE"
        RecrawlPolicy:
          RecrawlBehavior: CRAWL_EVERYTHING
        Role: !ImportValue RoleGlue-Arn
  TestDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "test-crawler-fraud"
      DatabaseName: "default"
      Classifiers:
        - !Ref GlueClassifier
      Targets:
        S3Targets:
          - Path: !Ref S3Path
          - Exclusions: ["fraudTrain.csv"]
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DELETE_FROM_DATABASE"
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_EVERYTHING
      Role: !ImportValue RoleGlue-Arn
  FraudDetectorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: frauddetector.amazonaws.com
            Action: sts:AssumeRole
      RoleName: FraudDetectorRoleS3Access
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess