Parameters:
  Nodes:
    Default: 5
    Description: "Number of DPU units"
    Type: "Number"
  Workers:
    Default: 8
    Description: "Number of workers of type WorkerType"
    Type: "Number"
  WorkerType:
    Default: G.1X
    Description: "WorkerType e.g Standard, G.1X, G.2X"
    Type: "String"
Resources:
    GlueDevEndpoint:
        Type: AWS::Glue::DevEndpoint
        Properties:
          Arguments: {"GLUE_PYTHON_VERSION": "3", "--enable-glue-datacatalog": ""}
          EndpointName: GlueTestEndpoint
          GlueVersion: "1.0"
          NumberOfWorkers: !Ref Workers
          RoleArn: !GetAtt [GlueNotebookRole,Arn]
          WorkerType: !Ref WorkerType
    GlueNotebookRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: "AWSGlueServiceNotebookRoleDefault"
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - glue.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        ManagedPolicyArns: [ "arn:aws:iam::aws:policy/AmazonS3FullAccess",
                              "arn:aws:iam::aws:policy/service-role/AWSGlueServiceNotebookRole",
                             "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess",
                              "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess" ,
                              "arn:aws:iam::aws:policy/AmazonEC2FullAccess"]
    SagemakerNotebookRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: "AWSGlueSagemakerNotebookRoleDefault"
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - sagemaker.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: PolicyforGlueSagemakerNotebook
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - 'kms:*'
                    - 'glue:*'
                  Resource: '*'
        ManagedPolicyArns:
              - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
              - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
              - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"