Parameters:
  DatasetType:
    Default: Interactions
    Description: "Type of dataset resource to create in personalize"
    Type: "String"
  SFDefBucket:
    Default: recommendation-sample-data
    Description: "step function definition file S3 bucket"
    Type: "String"
  SFDefKey:
    Default: movie-lens/sf-definition.json
    Description: "step function definition file S3 key"
    Type: "String"
Resources:
    PersonalizeDataset:
        Type: AWS::Personalize::Dataset
        Properties:
          DatasetGroupArn: !GetAtt [PersonalizeDatasetGroup, DatasetGroupArn]
          DatasetType: !Ref DatasetType
          Name: Recommend
          SchemaArn: !GetAtt [PersonalizeSchema, SchemaArn]
    PersonalizeDatasetGroup:
        Type: AWS::Personalize::DatasetGroup
        Properties:
          Name: RecommendGroup
    PersonalizeSchema:
        Type: AWS::Personalize::Schema
        Properties:
          Name: RecommendSchema
          Schema: |
            {
              "type": "record",
              "name": "Interactions",
              "namespace": "com.amazonaws.personalize.schema",
              "fields": [
                  {
                      "name": "USER_ID",
                      "type": "string"
                  },
                  {
                      "name": "ITEM_ID",
                      "type": "string"
                  },
                  {
                      "name": "TIMESTAMP",
                      "type": "long"
                  }
              ],
              "version": "1.0"
            }
    PersonalizeRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: "PersonalizeRole"
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - personalize.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        "ManagedPolicyArns": [ "arn:aws:iam::aws:policy/AmazonS3FullAccess",
                               "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess" ,
                                "arn:aws:iam::aws:policy/service-role/AmazonPersonalizeFullAccess"]
    GlueJob:
      Type: AWS::Glue::Job
      Properties:
        Command:
          Name: glueetl
          PythonVersion: "3"
          ScriptLocation: !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/scripts/personalize-glue-etl-movies.py"
        DefaultArguments:
          "--enable-continuous-cloudwatch-log": "true"
          "--enable-glue-datacatalog": "true"
          "--enable-job-insights": "true"
          "--enable-metrics": "true"
          "--job-bookmark-option": "job-bookmark-disable"
          "--job-language": "python"
        ExecutionProperty:
          MaxConcurrentRuns: 2
        MaxRetries: 0
        GlueVersion: 3.0
        WorkerType: Standard
        NumberOfWorkers: 4
        Timeout: 15
        Name: Recommendation-movies-transform
        Role: !ImportValue RoleGlue-Arn
    StepFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2008-10-17'
          Statement:
            - Sid: ''
              Effect: Allow
              Principal:
                Service: states.amazonaws.com
              Action: sts:AssumeRole
        RoleName: StepFunctionGluePersonalize
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
          - arn:aws:iam::aws:policy/service-role/AmazonPersonalizeFullAccess
          - arn:aws:iam::aws:policy/CloudWatchFullAccess
          - arn:aws:iam::aws:policy/AWSXrayFullAccess
    StateMachine:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        StateMachineName: GlueETLPersonalizeTraining
        DefinitionS3Location:
          Bucket: !Ref SFDefBucket
          Key: !Ref SFDefKey
        RoleArn: !GetAtt [StepFunctionRole, "Arn"]

